### ISSUE TITLE
Update to AndroidX?

### ISSUE THREAD

**Issue by JvmName** [grivos/Spanomatic#3]
I'm currently using v1.0.2 of Spanomatic, and I noticed that the internal `Utils.kt` is using `android.support.v4.content.ContextCompat` in a few places. 

Would you be open to migrating to AndroidX - e.g. using `androidx.core.content.ContextCompat`?

I'd be happy to help, I've done it before: 
- https://github.com/VictorAlbertos/RxActivityResult/pull/59
- https://github.com/vanniktech/RxPermission/pull/56

I know folks can use Jetifier, but given that Support Libs are officially deprecated, it'd be nice to win the Jetifier Tax back in my build 😄 

Let me know your thoughts!

**Comment by grivos** [comment]
Hey, thanks for the info.
Sure, migrating to AndroidX is something that needs to be done.
Create a pull request and I'll happily merge it.
