### ISSUE TITLE
Bintray Shutting Down May 2021 -- Host artifacts elsewhere?

### ISSUE THREAD

**Issue by JvmName** [grivos/Spanomatic#6]
Hi! Today JFrog (which owns Bintray/JCenter) announced that they're sunsetting Bintray/JCenter - the last day to access these repositories will be May 2021. jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter

I know a lot of tooling goes into artifact upload to a repository, so I wanted to throw a signal flare up now so nobody is caught by surprise on May 1.

**Comment by JvmName** [comment]
@grivos  In case it makes your life any easier, there's a tool that Martin Bonnin developed that seems to make this pretty straightforward: https://github.com/martinbonnin/vespene

**Comment by JvmName** [comment]
bumping this @grivos

**Comment by grivos** [comment]
@JvmName Thanks for reminding me.
I chose to move to JitPack because it's much easier.
(See this commit: 45e492dfa748b1e82facd14c15b590bc54ec4e0c)
I might reconsider migrating to Maven Central in the future.
